version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - mongodata:/data/db
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: max
      #   MONGO_INITDB_ROOT_PASSWORD: secret
      # - MONGO_INITDB_ROOT_SERNAME=max
    env_file:
      - ./env/mongo.env
    ports:
      - '27018:27017'
  backend:
    build: ./
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '8080:8080'
    volumes:
      - ./:/opt/project
      - /opt/project/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb


volumes:
  mongodata:

